### ISSUE TITLE
Improve build system: Do not calculate arc.h unnecessarily.

### ISSUE THREAD

**Issue by felipesanches** [moddevices/mod-pitchshifter#1]
I tried building Pitch Shifter and I noticed that the make.sh script is a bit "dumb" if compared to propper Makefiles... :-P 

It unconditionally runs the AtanTable.py python script that calculates a table of arc tangent values and stores it in a C header file called arc.h . As the script takes some time to run, it would be wise to create a propper Makefile that only generates the arc.h file if it does not yet exists or if it is older than a recent update to its dependency, the AtanTable.py script.

**Comment by falkTX** [comment]
This has been fixed with the makefile rework
