### ISSUE TITLE
Capo crashes when changing Lo-Fi to Normal fidelity

### ISSUE THREAD

**Issue by falkTX** [moddevices/mod-pitchshifter#12]
Happens 100% of the time after running in Lo-Fi for a few seconds.
Buffer size needs to be 256 frames.

**Comment by zonkmachine** [comment]
I trace this to 57b2051f8be2c7029a93f908bc99b32702169f94

**Comment by zonkmachine** [comment]
Also, **Step** need to be set to something other than 0 for the bug to show up.

**Comment by falkTX** [comment]
Fixed in efd26e6b02ddf9683ffae00a59ad72b5ab59d585
